# -*- coding: utf-8 -*-
"""Lab06.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t2wRfdzIN2vUIz6WFMKb0dCuksTgdC2v
"""

def encoder(password):
  rst = ""
  for i in password:
    rst += str(int(i)+3)
  return rst

# Encoder
def print_menu():
  print("Menu")
  print("-------------")
  print("1. Encode")
  print("2. Decode")
  print("3. Quit")

while True:
  print_menu()
  opt = int(input("Please enter an option: "))
  store = ""
  if opt == 1:
    password = input("Please enter your password to encode: ")
    store = encoder(password)
    print("Your password has been encoded and stored! ")

  if opt == 3:
    break

